language: php

php:
  - 5.6
  - 7.1
  - 7.2

env:
  - COMPOSER_OPTIONS='install --prefer-source'

before_install:
  - composer self-update

before_script:
  - composer $COMPOSER_OPTIONS

script:
  - ./bin/phpspec run --format=pretty